### PR TITLE
Feat: Added card component

### PR DESCRIPTION
**Pull request by sakleprajwal**
Live Priview Link : https://spacui-card-component.netlify.app/
Checkout the card component.

### CODE REVIEW

**Review by vijaytembugade — APPROVED** [review]
Looks great.  Good to go.

**Comment by nishasen** [comment]
Hey this looks good

**Comment by sakleprajwal** [comment]
> Hey this looks good

Thank you nisha

**Comment by sakleprajwal** [comment]
> Looks great. Good to go.

Thank you vijay

**Pull request merged**
