### PR TITLE
Feat: Added image and input component

### PR DESCRIPTION
**Pull request by sakleprajwal**
I have created pull request for image and input component.
Please review the same.
Live preview: https://spacui-image-input-component.netlify.app/

### CODE REVIEW

**Comment by sakleprajwal** [comment]
> everything looks great , just a suggestion try to decrease size of image to make it look better

Ho Raman, I have kept it's size 100% so that the responsiveness will be highlighted. Thanks for reviewing.

**Comment by vanshitalavange** [comment]
Everything looks fine. Great work Prajwal👍
Your component library looks really nice!

**Comment by raman1999** [comment]
OK

**Comment by sakleprajwal** [comment]
> Everything looks fine. Great work Prajwal👍 Your component library looks really nice!

Thank you Vanshita

**Pull request merged**
